### PR TITLE
tests: Unit tests using Catch2

### PR DESCRIPTION
**Pull request by sim590**
[Catch2][catch] is a lightweight and easy unit test framework holding completely in one header file. Unit tests that are to be imlpemented:

- [x] `dpaste::Bin::get/paste`;
- [x] `dpaste::Bin::code_from_dpaste_uri`;
- [x] `dpaste::Bin::data_from_stream`;
- [x] `dpaste::Node::get/paste`;
- [x] `dpaste::conf::getConfiguration`.

[catch]: https://github.com/catchorg/Catch2

### CODE REVIEW

**Comment by sim590** [comment]
This addresses issue #7.

**Comment by sim590** [comment]
For now, tests can only be compiled using `autotools`. I'm thinking about enabling it with CMake.

- [ ] support tests with CMake

**Comment by sim590** [comment]
Autotools compiles source code twice: once for building `dpaste` and another time for building the unit test program.

- [x] avoid building source code twice

**Comment by sim590** [comment]
I now avoid building twice by first building a static library before building `dpaste` binary and tests. Both link on the static library.

**Comment by aberaud** [comment]
looks good :-)

**Comment by sim590** [comment]
@aberaud: Have you seen the pirates? :skull_and_crossbones:

**Pull request merged**
